# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_ImT6CM3E1FhGs519RneGmOBKU3iOVO
"""

def can_king_move(x1, y1, x2, y2, checkerboard):
  if (x1, y1) == (x2, y2): # 判斷是否移動到原地
    return "No"

  if abs(x1 - x2) <= 1 and abs(y1 - y2) <= 1:
    if checkerboard[x2][y2] == 0: # 判斷是否有其他棋子擋住
      return "Yes"

  return "No"

# 輸入國王的目前位置與目標位置
x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())
print(can_king_move(x1, y1, x2, y2, checkerboard))